version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    #TODO
    environment:
      - DEBUG=True
      - SECRET_KEY=docker-secret-key-change-in-production

    command: python manage.py runserver 0.0.0.0:8000
