services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    #TODO
    environment:
      - DEBUG=false
      - SECRET_KEY=docker-secret-key-change-in-production

    # Quick fix: Auto-restart when container crashes
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 --workers 8 --preload --max-requests 20 --timeout 300 political_classifier.wsgi:application
